__author__ = 'karatel'


ERR_TRANSFER = {
    'INVALID_HASH': 101,
    'MISMATCHED_HASH': 102,
    'HUGE_FILE': 103,
    'FULL_DISK': 201,
    'LIMIT_REACHED': 202,
    'NOT_FOUND': 301,
    'LOST_FILE': 302,
    'INVALID_SIGNATURE': 401,
    'REPEATED_UPLOAD': True,
    'INVALID_DECRYPTION_KEY': 406,
}

ERR_AUDIT = {
    'INVALID_HASH': 101,
    'INVALID_SEED': 102,
    'LIMIT_REACHED': 103,
    'NOT_FOUND': 301,
    'INVALID_SIGNATURE': 401
}

ERR_BLACKLIST = 999
